// Run: node --test core/tilewgsl.test.mjs
// TILED_EXPORT.md §3/PR-1 — a golden snapshot of the emitted tile WGSL.
//
// Why this exists when tileseam.test.mjs already proves the algebra: that test
// executes the CPU tier's HAND-MIRRORED copy of the window. WGSL is compiled
// nowhere in CI (#206, nine days black on the GL tier), so nothing in the tree
// would notice the emitter drifting away from the copy the CPU tier mirrors —
// which is exactly how the three ray-gen copies diverge in the first place.
// This pins the emitted text verbatim, the frag_*.glsl pattern of
// standalone.test.mjs applied to WGSL.
//
// An EXCERPT, deliberately: a whole-shader golden would fail on every unrelated
// WGSL edit and get regenerated reflexively, which is how a golden stops being a
// gate. Only the tile blocks are pinned, so a diff here always means someone
// touched the tile path.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  buildWGSL,
  buildPostWGSL,
  TILE_WORD,
  TILEPX_WORD,
  GLOBALS_WORDS,
} from "./shader.js";

const FIXTURE = fileURLToPath(
  new URL("./__fixtures__/tile_wgsl.txt", import.meta.url),
);

// Slice from the line containing `from` through the line containing `to`.
// A missing anchor throws by name — that IS the drift alarm, and a clearer one
// than a 40-line unified diff.
function slice(src, from, to) {
  const lines = src.split("\n");
  const a = lines.findIndex((l) => l.includes(from));
  assert.notEqual(
    a,
    -1,
    `anchor not found in emitted WGSL: ${JSON.stringify(from)}`,
  );
  const b = lines.findIndex((l, i) => i >= a && l.includes(to));
  assert.notEqual(
    b,
    -1,
    `end anchor not found after ${JSON.stringify(from)}: ${JSON.stringify(to)}`,
  );
  return lines.slice(a, b + 1).join("\n");
}

// The blocks PR-1 owns, in emission order. Comments are stripped from the march
// ray-gen slices (they are long and rewritten freely); the code lines are not.
function tileBlocks() {
  const march = buildWGSL({ numericDE: false });
  const post = buildPostWGSL();
  const noComments = (s) =>
    s
      .split("\n")
      .filter((l) => !l.trim().startsWith("//"))
      .join("\n");
  return [
    [
      "globals struct members",
      noComments(
        slice(march, "  tile    : vec4f,", "  tilepx  : vec4f,"),
      ).replace(/\s+\/\/.*$/gm, ""),
    ],
    [
      "march fs signature",
      slice(march, "@fragment fn fs(", "@fragment fn fs("),
    ],
    [
      "ray-gen window",
      noComments(slice(march, "  let wx = ndc.x", "  let wy = ndc.y")),
    ],
    [
      "ray-gen perspective",
      slice(march, "  var rd = normalize(G.camFwd.xyz", "* G.camUp.xyz);"),
    ],
    [
      "ray-gen ortho",
      slice(march, "      + ((wx * orthoH)", "      + ((wy * orthoH)"),
    ],
    [
      "background gradient",
      noComments(slice(march, "  var bgY = uv.y;", "  let bg = s2l(")),
    ],
    ["post globals view", slice(post, "struct PG {", "struct PG {")],
    [
      "post absolute position",
      noComments(slice(post, "  var gpos = pos.xy;", "  }")),
    ],
    ["post vignette", slice(post, "  if (post.w > 0.0) {", "  }")],
    [
      "post dither",
      slice(post, "  o = o + vec3f((ign(gpos)", "  o = o + vec3f((ign(gpos)"),
    ],
  ]
    .map(([name, body]) => `── ${name} ──\n${body}`)
    .join("\n\n");
}

// Prepended so the fixture explains itself to whoever opens it after a failure.
const HEADER = `# GOLDEN — the tile blocks of the emitted WGSL (TILED_EXPORT.md §3/PR-1).
# Generated by core/tilewgsl.test.mjs from buildWGSL()/buildPostWGSL(); comments
# are stripped from the slices where they carry no semantics.
#
# A diff here means the tile path's emitted shader changed. That is not
# automatically wrong — but WGSL is compiled nowhere in CI, so it MUST be
# re-verified in a real browser (?renderer=webgpu and the ?tiled=WxH driver)
# before this file is regenerated. Do not regenerate to make the test green.

`;

test("emitted tile WGSL is byte-for-byte the golden", () => {
  const want = readFileSync(FIXTURE, "utf8");
  assert.equal(HEADER + tileBlocks() + "\n", want);
});

// ── the identity claim, pinned in the EMITTER and not only in the algebra ────

test("the untiled path is the identity: no literal window constants are emitted", () => {
  const march = buildWGSL({ numericDE: false });
  // The window is ALWAYS read from the uniform — never specialised into the
  // source with a 1.0/0.0 baked in, which would make the "bit-identical when
  // untiled" claim true by accident of one build and false for the tiled one.
  for (const f of ["G.tile.x", "G.tile.y", "G.tile.z", "G.tile.w"]) {
    assert.equal(
      march.split(f).length - 1,
      1,
      `${f} must be read exactly once in the ray-gen window`,
    );
  }
  // ndc.x/ndc.y must no longer reach the ray directly — everything goes through
  // wx/wy, or the ortho branch would silently keep an untiled projection.
  assert.ok(
    !march.includes("ndc.x * aspect * tanF"),
    "stale untiled perspective term",
  );
  assert.ok(
    !march.includes("ndc.x * aspect * orthoH"),
    "stale untiled ortho term",
  );
});

test("the tile blocks are identical across march variants", () => {
  // The window is upstream of every specialisation (ops, scene, hybrid, df64),
  // so a variant that emitted a different ray-gen would be a real bug — and the
  // single-variant golden above would not see it.
  const variants = [
    { numericDE: false },
    { numericDE: true },
    { ops: [] },
    { ops: null },
  ];
  const ref = slice(
    buildWGSL(variants[0]),
    "  let wx = ndc.x",
    "* G.camUp.xyz);",
  );
  for (const v of variants.slice(1)) {
    assert.equal(
      slice(buildWGSL(v), "  let wx = ndc.x", "* G.camUp.xyz);"),
      ref,
      `variant ${JSON.stringify(v)} emits a different ray-gen`,
    );
  }
});

test("word indices are appended, so no existing hand-written index moves", () => {
  assert.equal(TILE_WORD, 46);
  assert.equal(TILEPX_WORD, 47);
  assert.equal(GLOBALS_WORDS, 48);
  // The post/accum/bloom passes address the buffer as a raw vec4 array, so the
  // interpolated index has to be the constant and not a hand-typed 47.
  assert.ok(buildPostWGSL().includes(`G.w[${TILEPX_WORD}].w > 0.0`));
});
